version: "3.9"  # optional since v1.27.0

services:
  database:
    image: postgres
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_PASSWORD=p@assword123
      - POSTGRES_USER=sa
      - POSTGRES_DB=busbud
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/files:/mnt/db
